# baseURL = 'https://shami.blog/'
baseurl = "/"

languageCode = 'en-us'
title = "Shami's Blog"
theme = 'shami.blog'
Paginate = 10
googleAnalytics = "UA-34104225-1"
enableRobotsTXT = true

[params]
author = "Mohammad H. AlShami"

[permalinks]
post = "/:year/:month/:title"

