# baseURL = 'https://shami.blog/'
baseurl = "/"

languageCode = 'en-us'
title = "Shami's Blog"
theme = 'shami.blog'
pagination.pagerSize = 10
enableRobotsTXT = true

[params]
author = "Mohammad H. AlShami"
header = "Mohammad H. AlShami"
images = ["/profile.jpg"]

[permalinks]
post = "/:year/:month/:title"

